baseURL = "https://www.gofortli.net/"
languageCode = "en-us"
title = "Arturo Negrette"
theme = "hugo-theme-stack"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[Params]
  description = "My Corner of the Internet"
  ogImage = "pegasuslaunch.png"
  ogImagealt = "Sounding Rocket in Flight"


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
